-- MySQL Script generated by MySQL Workbench
-- Mon Jul 20 19:29:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema campanha2020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema campanha2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campanha2020` DEFAULT CHARACTER SET utf8mb4 ;
USE `campanha2020` ;

-- -----------------------------------------------------
-- Table `campanha2020`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`estados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `sigla` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `campanha2020`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`cidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(60) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `cidades_ibfk_1`
    FOREIGN KEY (`estado`)
    REFERENCES `campanha2020`.`estados` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9703
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `campanha2020`.`campanhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`campanhas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `candidato` VARCHAR(50) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `cidade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `estado` (`estado` ASC) VISIBLE,
  INDEX `cidade` (`cidade` ASC) VISIBLE,
  CONSTRAINT `campanhas_ibfk_1`
    FOREIGN KEY (`estado`)
    REFERENCES `campanha2020`.`estados` (`id`),
  CONSTRAINT `campanhas_ibfk_2`
    FOREIGN KEY (`cidade`)
    REFERENCES `campanha2020`.`cidades` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `campanha2020`.`typeuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`typeuser` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `campanha2020`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `snhpwd` VARCHAR(512) NULL DEFAULT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `campanha2020`.`userlicence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campanha2020`.`userlicence` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `emailid` INT(11) NULL DEFAULT NULL,
  `usertype` INT(11) NULL DEFAULT NULL,
  `dtactivation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `licencecode` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `emailid` (`emailid` ASC) VISIBLE,
  INDEX `usertype` (`usertype` ASC) VISIBLE,
  CONSTRAINT `userlicence_ibfk_1`
    FOREIGN KEY (`emailid`)
    REFERENCES `campanha2020`.`usuarios` (`id`),
  CONSTRAINT `userlicence_ibfk_2`
    FOREIGN KEY (`usertype`)
    REFERENCES `campanha2020`.`typeuser` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
